spring:
  jpa:
    properties:
      hibernate:
         show_sql: true
         format_sql: true
logging:
  level:
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace